apiVersion: lcm.openshift.io/v1alpha1
kind: ImageBasedGroupUpgrade
metadata:
  name: ibgu-ibisno
  namespace: default
spec:
  clusterLabelSelectors: 
    - matchExpressions:
      - key: name
        operator: In
        values:
        - ibisno1
        - ibisno3
        - ibisno4
  ibuSpec:
    seedImageRef: 
      image: registry.example.com/ibu/seed-sno:v42016
      version: 4.20.16
#      pullSecretRef:
#        name: "<seed_pull_secret>"
#    extraManifests: 
#      - name: example-extra-manifests
#        namespace: openshift-lifecycle-agent
    oadpContent: 
      - name: oadp-cm-example
        namespace: openshift-adp
  plan: 
    - actions: ["Prep", "Upgrade", "FinalizeUpgrade"]
    #- actions: ["Prep"]
      rolloutStrategy:
        maxConcurrency: 2
        timeout: 2400
