---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "seedztp"
  namespace: "seedztp"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "pullsecret-cluster-sno"
  #clusterImageSetNameRef: "img4.18.13-multi-appsub"
  clusterImageSetNameRef: "img4.20.16-multi-appsub"
  sshPublicKey: "<your ssh key>"
  clusterName: "seedztp"
  networkType: "OVNKubernetes"
  # installConfigOverrides is a generic way of passing install-config
  # parameters through the siteConfig.  The 'capabilities' field configures
  # the composable openshift feature.  In this 'capabilities' setting, we
  # remove all the optional set of components.
  # Notes:
  # - OperatorLifecycleManager is needed for 4.15 and later
  # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
  # - Ingress is needed for 4.16 and later
  #installConfigOverrides: |
  #  {
  #    "capabilities": {
  #      "baselineCapabilitySet": "None",
  #      "additionalEnabledCapabilities": [
  #        "NodeTuning",
  #        "OperatorLifecycleManager",
  #        "Ingress"
  #      ]
  #    }
  #  }
  # Include references to extraManifest ConfigMaps.
  #extraManifestsRefs:
  #  - name: sno-extra-manifest-configmap
  #extraLabels:
  #  ManagedCluster:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
  #    du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
  #    common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
  #    group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
  #    sites : "example-sno"
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 172.16.25.0/24
  serviceNetwork:
    - cidr: 172.30.0.0/16
  additionalNTPSources:
    - 172.16.15.1
  # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
  # please see Workload Partitioning Feature for a complete guide.
  cpuPartitioningMode: AllNodes
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - hostName: "seedztp.example.com"
      role: "master"
      bmcAddress: "redfish-virtualmedia://192.168.6.22:8443/redfish/v1/Systems/seedztp"
      bmcCredentialsName:
        name: "redfish-secret"
      bootMACAddress: "00:50:56:86:80:bc"
      # Use UEFISecureBoot to enable secure boot, UEFI to disable.
      bootMode: "UEFI"
      rootDeviceHints:
        deviceName: "/dev/sda"
      # disk partition at `/var/lib/containers` with ignitionConfigOverride. Some values must be updated. See DiskPartitionContainer.md in argocd folder for more details
      ignitionConfigOverride: |
        {
          "ignition": {
            "version": "3.2.0"
          },
          "storage": {
            "disks": [
              {
                "device": "/dev/sda",
                "partitions": [
                  {
                    "label": "var-lib-containers",
                    "sizeMiB": 0,
                    "startMiB": 250000
                  }
                ],
                "wipeTable": false
              }
            ],
            "filesystems": [
              {
                "device": "/dev/disk/by-partlabel/var-lib-containers",
                "format": "xfs",
                "mountOptions": [
                  "defaults",
                  "prjquota"
                ],
                "path": "/var/lib/containers",
                "wipeFilesystem": true
              }
            ]
          },
          "systemd": {
            "units": [
              {
                "contents": "# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target",
                "enabled": true,
                "name": "var-lib-containers.mount"
              }
            ]
          }
        }
      nodeNetwork:
        interfaces:
          - name: ens192
            macAddress: "00:50:56:86:80:bc"
        config:
          interfaces:
            - name: ens192
              type: ethernet
              state: up
              ipv4:
                enabled: true
                address:
                  - ip: 172.16.25.90
                    prefix-length: 24 
                dhcp: false
              ipv6:
                enabled: false
          dns-resolver:
            config:
              search:
              - example.com
              server:
              - 172.16.15.6
              - 172.16.15.8
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 172.16.25.1 
                next-hop-interface: ens192
                table-id: 254
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
