apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: guestbookphp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-sc
  volumeMode: Filesystem

